### ISSUE TITLE
Arrow lens won't let me set a nullable property to null

### ISSUE THREAD

**Issue by DeafLight** [arrow-kt/arrow-optics#71]
After posting this on [SO](https://stackoverflow.com/q/65202250/1679537) I assued that I might get an answer here.

Given this (extremely simplified) code :

```
@optics
data class MigrationStatus(val token: String?)

val m = MigrationStatus(null)
```

I can call

```
val m1 = MigrationStatus.token.modify(m) { "some token" }
```

But as the argument type is a non nullable `String`, how can I modify token back to `null` ? Of course

```
val m2 = MigrationStatus.token.modify(m1) { null }
```

does not compile.

The same happens when changing token type to an `Option<String>` when trying to set it to `None`, but I avoided it as it is now deprecated (which I'm not sure I like, but that's another matter).

Did I miss something obvious ?

**Comment by nomisRev** [comment]
Hey @DeafLight,
I missed your question on StackOverflow but I answered there to hopefully make it more visual for everyone.

If you have any suggestions or improvements for the [docs](https://github.com/arrow-kt/arrow-optics/tree/master/arrow-docs/docs/dsl), a PR would be very welcome!

**Comment by DeafLight** [comment]
Hi Simon,

Thanks a lot, and keep up the great work! Arrow is exactly what is missing to Kotlin to make it a real multi paradigm language :+1:

**Comment by nomisRev** [comment]
Very welcome! And Thanks for the support and using Arrow! 🙌
