### ISSUE TITLE
Move `lastOptionMonoid` & `firstOptionMonoid` to core.

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-optics#8]
See arrow-kt/arrow#1466 

Promote the `Monoid` instances from arrow-optics [firstOptionMonoid](https://github.com/arrow-kt/arrow/blob/e93c27d42340744d139d484596009b4548daf3dc/modules/optics/arrow-optics/src/main/kotlin/arrow/optics/predef.kt#L18) and [lastOptionMonoid](https://github.com/arrow-kt/arrow/blob/e93c27d42340744d139d484596009b4548daf3dc/modules/optics/arrow-optics/src/main/kotlin/arrow/optics/predef.kt#L26) to core, these can be used in `Foldable` to implement `firstOption` and `lastOption` as well.

`firstOption` is currently derived by `get(0)` but can be derived from `fold(lastOptionMonoid())`, in a similar way we can add `lastOption` to `Foldable` using `lastOptionMonoid`.

**Comment by Daniel-Jacob** [comment]
Shouldn't there be a ticket in arrow-core for adding this functionality from there and change this to a ticket for removing the lastOptionMonoid and firstOptionMonoid once that is done?

**Comment by nomisRev** [comment]
Hey @Daniel-Jacob,

I'm now wondering if we should add these in `core` since they're quite niche instances, and I've updated them for the Arrow Optics overhaul [here](https://github.com/arrow-kt/arrow-optics/pull/90/files#diff-e6e9c898738742621d955cae3104b3182f7e198a217faf4bd045c79323d9b73fR6).
I'm going to close this ticket, since I'm unsure if we should add it in Arrow Core. We can open the ticket on Arrow Core for discussion later if needed.

Thanks for bringing this up!
